const HOUR_IN_DAY = 24;
const MINUTE_IN_HOUR = 60;
const SEC_IN_MINUTE = 60;
const SEC_IN_HOUR = SEC_IN_MINUTE * MINUTE_IN_HOUR;
const SEC_IN_DAY = SEC_IN_MINUTE * MINUTE_IN_HOUR * HOUR_IN_DAY;

const Time = {
  HOUR_IN_DAY,
  MINUTE_IN_HOUR,
  SEC_IN_MINUTE,
  SEC_IN_HOUR,
  SEC_IN_DAY,
};

export default Time;
